#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 5) Ler um valor e escrever a mensagem É MAIOR QUE 10! 
# se o valor lido for maior que 10, caso contrário escrever NÃO É MAIOR QUE 10!

valor=float(input("Digite um valor: "))
if valor>10:
    print("É MAIOR QUE 10!")
else:
    print("NÃO É MAIOR QUE 10")
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")