#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 6) Ler um valor e escrever se é positivo ou negativo 
# (considere o valor zero como positivo).

valor=float(input("Digite um valor: "))
if valor>=0:
    print("O valor é positivo.")
else:
    print("O valor é negativo.")
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")