#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 3) Escreva um algoritmo para ler uma temperatura em graus 
# Fahrenheit, calcular e escrever o valor correspondente em graus Celsius 
# (baseado na fórmula abaixo): C= (F - 32)*5/9
# Observação: Para testar se a sua resposta está correta saiba que 100oC = 212F

temperatura_fahrenheit=float(input("Digite a temperatura em graus Fahrenheit: "))
temperatura_celsius=(temperatura_fahrenheit-32)*5/9
print("A temperatura em graus Celsius é:", temperatura_celsius, "°C")
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")